/* empty css                      */import{a as u,S as m,i}from"./assets/vendor-D0cagnvz.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&a(o)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const f="48662828-d5228b65b3bd2a50381de04cd",g="https://pixabay.com/api/";async function y(n){return(await u.get(g,{params:{key:f,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:9}})).data.hits}function h(n){const r=document.querySelector(".gallery"),s=n.map(({webformatURL:a,largeImageURL:e,tags:t,likes:o,views:l,comments:d,downloads:p})=>`<a href="${e}" class="gallery-item">
                    <img src="${a}" alt="${t}">
                    <div class="info">
                        <p class="text">Likes<br> <span>${o}</span></p>
                        <p class="text">Views<br> <span>${l}</span></p>
                        <p class="text">Comments<br> <span>${d}</span></p>
                        <p class="text">Downloads<br> <span>${p}</span></p>
                    </div>
                </a>`).join("");r.innerHTML=s}const b=document.getElementById("search-form"),L=document.getElementById("search-input"),v=document.querySelector(".gallery"),c=document.getElementById("loader");let x=new m(".gallery a");b.addEventListener("submit",async n=>{n.preventDefault();const r=L.value.trim();if(!r){i.warning({title:"Увага",message:"Будь ласка, введіть пошуковий запит!"});return}c.classList.remove("hidden"),v.innerHTML="";try{const s=await y(r);if(s.length===0){i.info({title:"Немає результатів",message:"Спробуйте інший пошуковий запит!"});return}h(s),x.refresh()}catch{i.error({title:"Помилка",message:"Щось пішло не так! Спробуйте ще раз."})}finally{c.classList.add("hidden")}});
//# sourceMappingURL=index.js.map
